"""empty message

Revision ID: 065e3d638a6a
Revises: 57809dda6d55
Create Date: 2019-06-04 21:05:03.316333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '065e3d638a6a'
down_revision = '57809dda6d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('href', sa.String(length=256), nullable=False))
    op.alter_column('project', 'to_language',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project', 'to_language',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('project', 'href')
    # ### end Alembic commands ###
