"""empty message

Revision ID: a1fa03b040ec
Revises: 439d940a63cc
Create Date: 2019-06-06 23:56:20.309904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1fa03b040ec'
down_revision = '439d940a63cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'translators_tasks', 'task', ['task_id'], ['id'])
    op.create_foreign_key(None, 'translators_tasks', 'user', ['translator_id'], ['id'])
    op.drop_column('translators_tasks', 'id')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.add_column('translators_tasks', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'translators_tasks', type_='foreignkey')
    op.drop_constraint(None, 'translators_tasks', type_='foreignkey')
    # ### end Alembic commands ###
